
[versions]
junit = "5.14.1"
hamcrest = "3.0"
teamcity = "2025.11"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }
sonarqube = { id = "org.sonarqube", version = "7.2.0.6526" }
teamcity = { id = "io.github.rodm.teamcity-environments", version = "1.5.6" }

[libraries]
teamcity-dsl-plugins = { module = "org.jetbrains.teamcity:configs-dsl-kotlin-plugins-latest", version = "1.0-SNAPSHOT" }
teamcity-dsl = { module = "org.jetbrains.teamcity:configs-dsl-kotlin-latest" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
teamcity-server-api = { module = "org.jetbrains.teamcity:server-api", version.ref = "teamcity" }
